### ISSUE TITLE
limit crawl length by run time

### ISSUE THREAD

**Issue by howell4c** [webrecorder/browsertrix-crawler#137]
Browsertrix Cloud has an option to limit run time.  I'd like to see a command-line option for this for local crawls as well.  

The existing `--timeout` option is per-page, `--limit` by number of pages doesn't catch sites that are just really slow, and `--depth` doesn't catch unexpectedly large shallow sites.

**Comment by ikreymer** [comment]
Actually, support for this will soon be available as part of the next beta!
You can use `--sizeLimit` and `--timeLimit` flags on this branch: https://github.com/webrecorder/browsertrix-crawler/tree/health-and-size-checks, which will stop the crawl if the size (in bytes) or time (in seconds) limits have been reached. The state is also saved so you could restart crawl after it has stopped due to either a time or size limit.

Let us know if you run into any issues with this, these features should make it into release soon.

**Comment by ikreymer** [comment]
Now released in 0.6.0!
