### ISSUE TITLE
What's your registry strategy?

### ISSUE THREAD

**Issue by rgaudin** [webrecorder/browsertrix-crawler#260]
Given `webrecorder/browsertrix-crawler` images are solely pushed to Docker Hub at the moment;
that [webrecorder](https://hub.docker.com/u/webrecorder) is a *Community Organization*;
and that such organizations [will soon be prevented from pushing to Docker Hub](https://www.docker.com/blog/we-apologize-we-did-a-terrible-job-announcing-the-end-of-docker-free-teams/)…

We'd like to know what your plans are: switch to another registry such as ghcr.io (in this case we need to adjust our reference to the image) or pay a subscription to the Hub or get accepted in their OSS Program… in which cases we don't have to do anything.

**Comment by ikreymer** [comment]
Thanks for bringing this up! I've just requested a conversion of 'webrecorder' to a personal account, since we don't really need multiple users or any of the other features there, just storage of Docker images.
We will also look into alternative registry options as a backup as well, and may consider the OSS registry.
All of our tools are open-source, but I don't know if we qualify for their 'not being able to charge for any services for any tools enhancements' requirements, so we'll see.
Will keep this issue open until we have a final resolution.

**Comment by tw4l** [comment]
Update: Now that Docker has reversed their plan to sunset the Free Team plan, we will be sticking with Docker Hub at least for the foreseeable future and the current image references will continue to work.
