### ISSUE TITLE
Allow switching capturing backend from pywb to warcprox

### ISSUE THREAD

**Issue by Sanqui** [webrecorder/browsertrix-crawler#294]
[pywb](https://github.com/webrecorder/pywb) uses [warcio](https://github.com/webrecorder/warcio) which comes with a number of unresolved data integrity issues[^1].  [warcprox](https://github.com/internetarchive/warcprox) is another WARC generating proxy developed by the Internet Archive.  A cursory search shows that Browsertrix Crawler doesn't have much pywb-specific code[^2].  It might not be very difficult to make the proxy choice flexible.  Would implementing the option to use warcprox for WARC recording be of interest for the project?

[^1]: https://github.com/webrecorder/warcio/issues?q=is%3Aopen+author%3AJustAnotherArchivist
[^2]: https://github.com/search?q=repo%3Awebrecorder%2Fbrowsertrix-crawler%20pywb&type=code

**Comment by ikreymer** [comment]
warcio is a general purpose WARC library, and there's many edge cases, especially reading WARCs created by other tools, so I don't think its fair to say it has 'data integrity issues' or that the crawler does.

part of what pywb does here is also do is record-time rewriting with fuzzy matching, to ensure youtube videos and other types of video are captured correctly, which is not possible with a direct proxy only approach as in warcprox.

That being said, we are also working on a fully-node based recorder the will remove the pywb dependency, while maintaining the high-fidelity archiving baseline, which you can follow here: https://github.com/webrecorder/browsertrix-crawler/tree/recorder-work
This approach gets the data directly from the browser, rather than via HTTP proxy, but as everything, will have other trade-offs such as HTTP/2 connections, no MITM cert, but relying on data from the browser.
You can check out that branch if you'd like, though its still in heavy development.

Once we have that, I suppose an option to use an alternative/third-party proxy will still be easier to add, and can make sure we support it.

**Comment by ikreymer** [comment]
Actually, you can already choose a different proxy, simply by passing in these variables, eg:
```
docker run --network host -e PROXY_HOST=localhost -e PROXY_PORT=8000 ...
```
You can then run warcprox locally on localhost:8000 to crawl through that instead if you'd like.

Closing for now as no further action needed here, but happy to answer more questions!
