### ISSUE TITLE
Playwright persistent browser context causing memory issues

### ISSUE THREAD

**Issue by tw4l** [webrecorder/browsertrix-crawler#298]
The switch from Puppeteer to Playwright in 0.9 has resulted in users reporting memory issues during crawls. This seems to be related to a Playwright bug: https://github.com/microsoft/playwright/issues/6319

We will need to investigate launching new browser contexts periodically rather than using a persistent browser context to avoid these memory issues (see https://github.com/microsoft/playwright/issues/6319#issuecomment-1227405461). We may want to look into serializing the crawler state via the following method: https://playwright.dev/docs/api/class-browsercontext#browser-context-storage-state. There is a companion parameter to `Browser.newContext` to then load that state into a new browser context: https://playwright.dev/docs/api/class-browser#browser-new-context-option-storage-state.

We may eventually want to see if we should store browser state as these JSON blobs rather than via the current profile system.

**Comment by ikreymer** [comment]
Create a quick test setup that attempts to create a new context/page whenever a page is being closed, to reduce memory usage, as otherwise memory is not cleaned up by playwright until context is closed.

**Comment by ikreymer** [comment]
After some extensive testing, including adding support for switching between puppeteer and playwright we've found the following:

- The Playwright `page.route()` functionality, which is used for BlockRules and AdBlockRules is a major source of leaks.
It appears that support for 'long-running' sessions is not a priority, as mentioned here:
https://github.com/microsoft/playwright/issues/6319#issuecomment-826873539 and with this issue
https://github.com/microsoft/playwright/issues/20765 because playwright is optimized for short-lived tests.
- It's possible to try a different approach, using an incognito context and closing the playwright browser context (not just the page) every few pages. This requires additional work and may create additional overhead, but generally seems to lower the footprint with `page.route()`. This was not needed when using Puppeteer `page.on('request', ...)`
- Even without using page.route and hacking together a CDP-based solution for request routing, (see work on: https://github.com/webrecorder/browsertrix-crawler/tree/new-context-per-page) playwright still ends up using more memory than the same crawl in puppeteer.

- @tw4l for performed some extensive heavy-testing with the same crawl config and got the following results, with playwright-based driver crashing while puppeteer-driver did not. Both were long-running browser context approach.

Based on these results, it seems like the answer is in favor of moving back to Puppeteer (but not Puppeteer-cluster!).
The architecture of the crawler is now much improved and its not hard to switch between the two, and the API surface area is mostly small - we are doing a lot of things directly via CDP sessions anyway.

If anyone has any feedback / thoughts / suggestions, please let us know here. We want to ensure Browsertrix Crawler can continue to run in low-memory environments, and the browser uses a lot of memory, so this is pretty critical to keep the memory in the crawler node process as low as possible.

Tessa's testing results. Memory usage obtained from `process.memoryUsage()`

```
Browsertrix Crawler 0.10 memory testing

Setup

- Domain crawl of Webrecorder website
- 2 extra hops
- 500 page limit
- 4 workers
- WACZ generation

Puppeteer - Chrome - pop_os

- Run time: ~15 mins
- Crashed?: no

- Max heap total: 89.5 MB
- Average heap total: ~75 MB toward beginning of crawl, ~88 MB by end

- Max heap used: 64 MB
- Average heap used: 45-60 MB

Puppeteer - Chromium - macOS

- Run time: ~18 mins
- Crashed?: no

- Max heap total: 86 MB
- Average heap total: 75-80 MB

- Max heap used: 60 MB
- Average heap used: 45-55 MB

Playwright - Chrome - pop_os
 
- Run time: Crashed after ~19 mins
- Crashed?: yes, after 438 pages (stuck in loop trying to get new page)

- Max heap total:  138 MB
- Average heap total: steadily increased over course of crawl to max

- Max heap used:  110 MB
- Average heap used: steadily increased over course of crawl to max


Playwright - Chromium - macOS

- Run time: Crashed after ~21 mins
- Crashed?: yes, after 427 pages (stuck in loop trying to get new page)

- Max heap total:  153 MB
- Average heap total: steadily increased over course of crawl to max

- Max heap used:  116 MB
- Average heap used: steadily increased over course of crawl to max
```

**Comment by ikreymer** [comment]
Switched to puppeteer for 0.10.0-beta.0
