### ISSUE TITLE
Full-page screenshots missing content

### ISSUE THREAD

**Issue by ArtHoff** [webrecorder/browsertrix-crawler#299]
HI, I'm using the --screenshot fullPage option and it works great on most content, however on this page (https://nteconomy.nt.gov.au/labour-market?expanded=1) it won't show the graphics, except for those at the top of the page. All others show white space. 

The archived page looks fine and all graphs pop up after a few seconds. It's just the screenshot that's incomplete.

This is the command I'm using (with browsertrix-crawler version 0.9.1):
`podman run -v $PWD/crawls:/crawls/ -it webrecorder/browsertrix-crawler crawl --url https://nteconomy.nt.gov.au/labour-market?expanded=1 --generateWACZ --text --scopeType page --collection labour-market --screenshot fullPage`

**Comment by tw4l** [comment]
@ArtHoff I'm able to reproduce your issue and haven't yet been able to resolve it with the available crawler options like `--waitUntil` or even manually adding some additional time before the snapshot is taken. Will continue to investigate.

**Comment by ArtHoff** [comment]
Thank you @tw4l

**Comment by tw4l** [comment]
Hi @ArtHoff, apologies for the delay. I think the issue is that we need to make sure everything has rendered before taking the screenshot, and our options to add delays aren't sufficient for the task, so some customization work on your end would be necessary.

We currently have two ways that this could be accomplished with the crawler:
- With a driver (see the [default driver](https://github.com/webrecorder/browsertrix-crawler/blob/main/defaultDriver.js) for the general structure and some examples [here](https://github.com/webrecorder/dashboard-custom-drivers)). Drivers are [Puppeteer](https://pptr.dev/) scripts that can be used to customize the behavior taken on page load.
- With a behavior (see [Browsertrix Behaviors](https://github.com/webrecorder/browsertrix-behaviors/)]

In general, behaviors are better for repeated/general use cases (e.g. autoscroll, Twitter), whereas drivers are a bit easier to get started with and better for one-time customization.
