### ISSUE TITLE
Windows 1251 (cyrillic) encoded text incorrectly encoded

### ISSUE THREAD

**Issue by rgaudin** [webrecorder/browsertrix-crawler#36]
When scraping a website encoded in Windows Cyrillic (windows-1251), the convertion to UTF-8 is faulty, resulting in tons of `пїЅпїЅпїЅпїЅпїЅ` strings.

- Sample website: https://sattvinfo.net/
- Sample ZIM (valid only 7d from now) https://s3.us-west-1.wasabisys.com/org-kiwix-zimit/other/sattvinfo.net_99fa2e51.zim
- Recipe took 50mn to generate this 130MB ZIM.

Logs shows 2 instances of `[WARNING] Some characters could not be decoded, and were replaced with REPLACEMENT CHARACTER.`

Hint on what to do [on stackoverflow](https://stackoverflow.com/questions/8693400/converting-from-windows-1251-to-utf-8-in-node-js)

**website**
![Screen Shot 2021-03-26 at 09 58 18](https://user-images.githubusercontent.com/57929/112454606-c52ea280-8d50-11eb-945c-3000a7636325.png)

**ZIM**

![Screen Shot 2021-03-26 at 09 59 00](https://user-images.githubusercontent.com/57929/112454597-c364df00-8d50-11eb-8802-1e3c44392a69.png)

**Comment by ikreymer** [comment]
This is actually an issue with replay, in wabac.js, and I think same issue as webrecorder/archiveweb.page#20

The fix is to not use utf-8 encoding when parsing html (and also js and css) but to simply use latin-1, as we're only interested in parsing and rewriting ascii characters (inserting a URL prefix, which will be ascii).

We then leave it to the browser to actually decode using the content-type exactly as it would the live site.

It seems `TextDecoder("latin-1")` doesn't quite always work, and there's no longer a reverse `TextEncoder("utf-8")` so the solution includes adding simple encode/decode functions (also what Buffer does) to ensure everything is consistent.

With the fix in wabac.js, this site as well as the one mentioned in webrecorder/archiveweb.page#20
should work.

For Zimit, this will require updating the wabac.js to the latest version also.

**Comment by rgaudin** [comment]
Thanks!

**Comment by ikreymer** [comment]
Can now confirm a one-page crawl of this page renders correctly in latest replayweb.page, so closing this.
