### ISSUE TITLE
pages.jsonl missing required ts timestamp field

### ISSUE THREAD

**Issue by halmos** [webrecorder/browsertrix-crawler#560]
According to the wacz `pages.jsonl` spec (https://specs.webrecorder.net/wacz/1.1.1/#pages-jsonl), the `url` and `ts` fields are required for each entry line. However, the `pages.jsonl` file generated by browsertrix does not appear to include the timestamp. 

Furthermore, the `datapackage.json` does not always (ever?) include the optional `mainPageUrl` (https://specs.webrecorder.net/wacz/1.1.1/#datapackage-json).

When determining the order of pages scraped, can we rely on the order of the pages.jsonl document? ie. can we assume that the first url line is the initial seed url?

**Comment by ikreymer** [comment]
> According to the wacz `pages.jsonl` spec (https://specs.webrecorder.net/wacz/1.1.1/#pages-jsonl), the `url` and `ts` fields are required for each entry line. However, the `pages.jsonl` file generated by browsertrix does not appear to include the timestamp.
> 

Which version of the crawler are you using? Since 1.x, it is always included in pages.jsonl.
In earlier versions, I believe it was generated via py-wacz, and added to the pages.jsonl in the WACZ but maybe not the one in the directory.

> Furthermore, the `datapackage.json` does not always (ever?) include the optional `mainPageUrl` (https://specs.webrecorder.net/wacz/1.1.1/#datapackage-json).

We should probably change the wording, since these are optional, and only makes sense when there is only one seed. 

> When determining the order of pages scraped, can we rely on the order of the pages.jsonl document? ie. can we assume that the first url line is the initial seed url?

Yes, and in 1.1.x version, seeds only are written to pages.jsonl, other pages are written to extraPages.jsonl

**Comment by halmos** [comment]
Ah, yes, we were reviewing some wacz archives produced by an earlier version of Browsertrix when this issue arose. I just tested with the latest version and it does in fact include the timestamp in the pages.jsonl file. 

Many thanks for your quick response!
