### ISSUE TITLE
Browser Crash & Docker Exit Code

### ISSUE THREAD

**Issue by gitreich** [webrecorder/browsertrix-crawler#683]
Version 1.2.4 sometimes gets interrupted with the following message (happens specially long duration crawls):
Browser disconnected (crashed?), interrupting crawl","details":{}}

In this case the Docker Exit Code is 11

I would recomment to use Docker Exit Code 9 in this case as 11 is also the Exit Code for hitted Time / Disk Limit and 9 is for an Application Error

**Comment by ikreymer** [comment]
Hm, perhaps we can add more distinct error codes. error code 9 is when a crawl is considered to have failed altogether, I believe. 11 is for any kind of interruption of the crawl, but perhaps could be more specific if its a browser crash rather than a limit reached.

Or, can add more distinct error for the different interrupt reasons.. though that'll require changes in Browsertrix
I think differentiating this type of unexpected interrupt is fair
