### ISSUE TITLE
Improved Crawl Log Data

### ISSUE THREAD

**Issue by ikreymer** [webrecorder/browsertrix-crawler#74]
Determine what crawl logs should be generated to help debug crawl.
The page list (stored in `pages.jsonl`) already includes info on what pages were visited and when.
Possible additions:
- Page crawl graph data? (seed and crawl depth of each page)
- Behavior state log?
- Page resources? (which pages were each resources loaded from?)

Thinking the crawl graph data per page (seed and depth) and additional logging of behaviors would be most useful. The page resources will of course be available in the cdx.

In future, a pageId may also be added to WARC headers to be able to better map resources->page

**Comment by iolantheith** [comment]
The Information you shared above is great. I have been reading all you shared here. In this you explained everything very well. If i want any further guideline we will contact you here https://newjerseyloteryresults.com/ Thanks

**Comment by tw4l** [comment]
@despens it seems like the main outstanding issue from your comment is that getting TLDs from `pages.jsonl` can be difficult because of the presence of extracted full text, which seems best handled in a separate issue. I'm going to close this issue and we can track that in https://github.com/webrecorder/browsertrix-crawler/issues/203. Thanks!
